server:
  port: 8090

  error:
    include-message: never
    include-stacktrace: never

spring:

  datasource:
    # Local test server Postgres
    url: jdbc:mysql://localhost:3306/foodlify_api
    username: postgres
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #      ddlAuto: validate
      ddlAuto: create-drop
    showSql: true
    properties:
      hibernate:
        format_sql: false
    database: mysql
    databasePlatform: org.hibernate.dialect.MySQLDialect


application:
  security:
    jwt:
      secret-key: 4528482B4D6251655468576D597133743677397A24432646294A404E635266556A586E327234753778214125442A472D4B6150645367566B5970337336763879
      expiration: 86400000 # One day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      hibernate: error