server:
  port: 8090
  error:
    include-message: always
    include-binding-error: always

spring:

  datasource:
    # Local test server Postgres
    url: jdbc:postgresql://localhost:5432/foodlify_api
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      #      ddlAuto: validate
      ddlAuto: create-drop
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect


application:
  security:
    jwt:
      secret-key: 4528482B4D6251655468576D597133743677397A24432646294A404E635266556A586E327234753778214125442A472D4B6150645367566B5970337336763879
      expiration: 86400000 # One day
      refresh-token:
        expiration: 604800000 # 7 days